<?xml version="1.0"?>

<robot name="tugbot" xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:arg name="robot_namespace" default="/" />
  
  <xacro:property name="M_PI" value="3.14159"/>

  <xacro:macro name="tugbot_wheel" params="wheel_prefix *joint_pose">
		<link name="${wheel_prefix}_wheel_link">
			<inertial>
				<mass value="2.637" />
				<origin xyz="0 0 0" />
				<inertia  ixx="0.02467" ixy="0" ixz="0" iyy="0.04411" iyz="0" izz="0.02467" />
			</inertial>
			<visual>
				<origin xyz="0 0 0" rpy="0 0 ${M_PI/2}" />
				<geometry>
					<mesh filename="package://tugbot_description/meshes/wheel.dae" />
				</geometry>
			</visual>
			<collision>
				<origin xyz="0 0.03 0" rpy="${M_PI/2} 0 0" />
				<geometry>
					<cylinder length="${wheel_length}" radius="${wheel_radius}" />
				</geometry>
			</collision>
		</link>

		<gazebo reference="${wheel_prefix}_wheel_link">
			<mu1 value="1.0"/>
			<mu2 value="1.0"/>
			<kp value="10000000.0" />
			<kd value="1.0" />
			<fdir1 value="1 0 0"/>
		</gazebo>

		<joint name="${wheel_prefix}_wheel" type="continuous">
			<parent link="base_link"/>
			<child link="${wheel_prefix}_wheel_link"/>
			<xacro:insert_block name="joint_pose"/>
			<axis xyz="0 1 0" rpy="0 0 0" />
		</joint>

		<transmission name="${wheel_prefix}_wheel_trans" type="SimpleTransmission">
			<type>transmission_interface/SimpleTransmission</type>
			<actuator name="${wheel_prefix}_wheel_motor">
				<mechanicalReduction>1</mechanicalReduction>
			</actuator>
			<joint name="${wheel_prefix}_wheel">
				<hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
			</joint>
		</transmission>

	</xacro:macro>



  <!-- Base Size -->
  <xacro:property name="base_x_size" value="0.42" />
  <xacro:property name="base_y_size" value="0.22" />
  <xacro:property name="base_z_size" value="0.17" />

  <!-- Wheel Mounting Positions -->
  <xacro:property name="wheelbase" value="0.26" />
  <xacro:property name="track" value="0.22" />
  <xacro:property name="wheel_vertical_offset" value="0.02" />

  <!-- Wheel Properties -->
  <xacro:property name="wheel_length" value="0.05" />
  <xacro:property name="wheel_radius" value="0.08" />

  <!-- Base link is the center of the robot's bottom plate -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://tugbot_description/meshes/base_link.dae" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0.04" rpy="0 0 0" />
      <geometry>
        <box size="${base_x_size} ${base_y_size} ${base_z_size/2}"/>
      </geometry>
    </collision>
  </link>

    <link name="inertial_link">
    <inertial>
      <mass value="10.0" />
      <origin xyz="-0.00065 -0.085 0.062" />
      <inertia ixx="0.6022" ixy="-0.02364" ixz="-0.1197" iyy="1.7386" iyz="-0.001544" izz="2.0296" />
    </inertial>
  </link>

  <joint name="inertial_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="inertial_link" />
  </joint>

  <xacro:tugbot_wheel wheel_prefix="front_left">
    <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:tugbot_wheel>
  <xacro:tugbot_wheel wheel_prefix="front_right">
    <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 ${M_PI}" />
  </xacro:tugbot_wheel>
  <xacro:tugbot_wheel wheel_prefix="rear_left">
    <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
  </xacro:tugbot_wheel>
  <xacro:tugbot_wheel wheel_prefix="rear_right">
    <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 ${M_PI}" />
  </xacro:tugbot_wheel> 

  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>$(arg robot_namespace)</robotNamespace>
    </plugin>
  </gazebo>

</robot>